<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Atendimento Espiritual</span> 
        <br>
        O <b>Atendimento Espiritual</b> no Centro Espírita abrange as seguintes atividades:
        <ul>
            <li><span class="boldit">Recepção</span>;</li>
            <li><span class="boldit">Atendimento Fraterno pelo Diálogo</span>;</li>
            <li><span class="boldit">Reunião Pública para explanação do Evangelho à Luz da Doutrina Espírita</span>;</li>
            <li><span class="boldit">Atendimento pelo Passe</span>;</li>
            <li><span class="boldit">Irradiação</span>;</li>
            <li><span class="boldit">Evangelho no Lar e no Coração</span>.</li>
        </ul>
    </div>
    
    <br>    
    
    
    <!-- Horários -->
    <div>
        <span class="destaque">Horários e Exclarecimentos</span>
        <br>
    </div>
    <div>
        <p>
            O atendimento fraterno é realizado conforme as orientações da FEB e do CEERJ e ocorre antes das 
            reuniões públicas.
        </p>
        <p>
            Deve ser agendado na recepção do CEI, podendo ocorrer no mesmo dia.
        </p>
        <p>
            No atendimento fraterno serão dadas orientações para aqueles necessitados de auxílio espiritual.
        </p>
        <ul>
            <li><span class="boldit">Segunda-feira</span> - de 14:00h às 14:50h;</li>
            <li><span class="boldit">Terça-feira</span> - de 19:00h às 19:50h;</li>            
            <li><span class="boldit">Quarta-feira</span> - de 18:50h às 19:20h;</li>
            <li><span class="boldit">Sexta-feira</span> - de 18:50h às 19:20h;</li>
            <li><span class="boldit">Sábado</span> - de 19:00h às 19:30h;</li>
        </ul>
        <p>
            O atendimento fraterno tem como objetivo primacial receber bem e orientar com segurança todos 
            aqueles que o buscam.
        </p>
        <p>
            Não se propõe a resolver os desafios nem as dificuldades, eliminar as doenças nem os sofrimentos, 
            mas propor ao cliente os meios hábeis para a própria recuperação.
        </p>
        <p>
            Apoiando-se nos postulados espíritas, o atendimento fraterno abre perspectivas novas e projeta 
            luz naqueles que se debatem nos dédalos das aflições.
        </p>
        <p>
            Concomitantemente, o atendimento fraterno, em razão dos propósitos que persegue e das 
            circunstâncias em que ocorre, faculta aos Espíritos nobres adequado socorro ao cliente, 
            que deverá permanecer receptivo ao mesmo.
        </p>
        <p>
            Nessa ocasião, tem início a ação fluídica, o auxílio bio-energético, a inspiração, que lhe 
            propiciarão a mudança de clima mental, de psicosfera habitual, facultando-lhe a transformação 
            interior para melhor e a rearmonização da alma que interagirá na aparelhagem orgânica.
        </p>
        <p>
            O Atendimento Fraterno não tem como finalidade fazer prosélitos. De igual
            modo não se deve converter em consultório psicológico.
        </p>
        <p>
            Uma coisa é certa: o trabalho do Atendimento tem compromisso com a
            discrição e o anonimato, por força de um impositivo ético que é comum a todas
            as disciplinas voltadas para a saúde física ou moral da criatura humana.
        </p>
    </div>   
    
   
</div>