<div id="boletim">
    <div class="title_boletim">
        PALAVRAS
    </div>
          
    <p class="epistola">
        <span class="txt_evan">"Da mesma boca procede bênção e maldição." - (TIAGO, 3:10.)</span>
    </p>

    <div class="txt_boletim">
        <p>
        Nunca te arrependerás:
        </p>            
        <p>
          De haver ouvido cem frases, pronunciando simplesmente uma ou outra pequena
observação.
        </p>    
        <p>
        De evitar o comentário alusivo ao mal, qualquer que seja.
        </p>
        <p>
        De calar a explosão de cólera.
        </p>
        <p>
        De preferir o silêncio nos instantes de irritação.
        </p>
        <p>
        De renunciar aos palpites levianos nas menores controvérsias.
        </p>
        <p>
        De não opinar em problemas que te não dizem respeito.
        </p>
        <p>
        De esquivar-te a promessas que não poderias cumprir.
        </p>
        <p>
        De meditar muitas horas sem abrir os lábios.
        </p>
        <p>
        De apenas sorrir sempre que visitado pela desilusão ou pela amargura.
        </p>
        <p>
        De fugir a reclamações de qualquer natureza.
        </p>
        <p>
         De estimular o bem sob todos os prismas.
        </p>
        <p>
        De pronunciar palavras de perdão e bondade.
        </p>
        <p>
        De explanar sobre o otimismo, a fé e a esperança.
        </p>
        <p>
        De exaltar a confiança no Céu.
        </p>
        <p>
         De ensinar o que seja útil, verdadeiro e santificante.
        </p>
        <p>
        De prestar informações que ajudem aos outros.
        </p>
        <p>
        De exprimir bons pensamentos.
        </p>
        <p>
        De formular apelos à fraternidade e à concórdia.
        </p>
        <p>
         De demonstrar benevolência e compreensão.
        </p>
        <p>
        De fortalecer o trabalho e a educação, a justiça e o dever, a paz e o bem, ainda
mesmo com sacrifício do próprio coração.
        </p>
        <p>
        Examina o sentido, o modo e a direção de tuas palavras, antes de pronunciá-las.
        </p>
        <p>
        Da mesma boca procede bênção ou maldição para o caminho.
        </p>
            
    </div>

    <p class="epistola">
        Do livro "Vinha de Luz"
        <br>
        <span style="color: #666;">Autor Espiritual:</span> Emmanuel
        <br>
        <span style="color: #666;">Médium:</span> Francisco Cândido Xavier
    </p>
</div> <!-- end div Boletim -->

