<div id="boletim">
    <div class="title_boletim">
        TRANSFORMAÇÃO
    </div>
          
    <p class="epistola">
        <span class="txt_evan">"Na verdade, nem todos dormiremos, mas todos seremos transformados."</span> - Paulo.
        (I CORÍNTIOS, 15:51.)
    </p>

    <div class="txt_boletim">
        <p>Refere-se o apóstolo dos gentios a uma das mais belas realidades da vida
    espiritual.</p>
            
        <p>    Nos problemas da morte, as escolas cristãs, trabalhadas pelas cogitações
    teológicas de todos os tempos, erigiram teorias diversas, definindo a situação da criatura,
    após o desprendimento carnal. É justo que semelhante situação seja a mais diversificada
    possível. Ninguém penetra o circulo da vida terrena em processo absolutamente uniforme,
    como não existem fenômenos de desencarnação com analogia integral. Cada alma possui
    a sua porta de "entrada" e "saída", conforme as conquistas próprias.
        </p>
    
        <p>
        Fala-se demasiadamente em zonas purgatoriais, em trevas exteriores, em regiões
de sono psíquico.
        </p>
        <p>
        Tudo isso efetivamente existe em plano grandioso e sublime que, por enquanto,
transcende o limitado entendimento humano.
        </p>
        <p>
       Todos os que se abeberam nas fontes puras da verdade, com o Cristo, devem
guardar sempre o otimismo e a confiança.
        </p>
        <p>
        "Nem todos dormiremos" - diz Paulo. Isto significa que nem todas as criaturas
caminharão às tontas, nas regiões mentais da semi-inconsciência, nem todas serão
arrebatadas a esferas purgatoriais e, ainda que tais ocorrências sucedessem, ouçamos,
ainda, o abnegado amigo do Evangelho, quando nos assevera - "mas todos seremos
transformados".
        </p>
        <p>
        Paulo não promete sofrimento inesgotável nem repouso sem-fim. Promete
        transformação.
        </p>
        <p>
        Ninguém parte ao chamado da Vida Eterna senão para transformar-se.
        </p>
        <p>
        Morte do corpo é crescimento espiritual.
        </p>
        <p>
        O túmulo numa esfera é berço em outra.
        </p>
        <p>
        E, como a função da vida é renovar para a perfeição, transformemo-nos para o
        bem, desde hoje.
        </p>
            
    </div>

    <p class="epistola">
        Do livro "Vinha de Luz"
    </p>
</div> <!-- end div Boletim -->

