<div id="boletim">
    <div class="title_boletim">
        <?php echo $texto['titulo']; ?>
    </div>
          
    <p class="epistola">
        <span class="txt_evan"><?php echo $texto['citacao']; ?></span>
    </p>

    <div class="txt_boletim">
        <?php
            $pagina = explode("\n", $texto['texto']);
            
            foreach ($pagina as $paragrafo): ?>
        
                <p><?php echo $paragrafo; ?></p>
            
            <?php endforeach; ?>
    </div>

    <p class="epistola">
        Do livro "<?php echo $texto['livro']; ?>"
        <br>
        <span style="color: #666;">Autor Espiritual:</span> Emmanuel
        <br>
        <span style="color: #666;">Médium:</span> Francisco Cândido Xavier
    </p>
</div> <!-- end div Boletim -->

