<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Grupo Joanna de Ângelis</span> 
        <br>
        <b>Conhecendo a Si Mesmo (Estudo da Série Psicológica)</b>
    </div>
    <!-- programação -->
    <div>
        <table>
            <thead>
                <th>Local</th>
                <th>Conteúdo</th>
                <th>Horário</th>
            </thead>
            <tbody>
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Sábado - (quinzenalmente, 2° e 4° sábados)</td>
                </tr>
                <tr>
                    <td>Bezerra de Menezes</td>
                    <td>Estudo das Obras de Joanna de Ângelis a luz do Evangelho</td>
                    <td>18:15h às 19:30h</td>
                </tr> 
            </tbody>
        </table>
    </div>
        
    <br>
    <hr>
    <br>
        
    <div class="txt_esde">
        <span class="destaque">Grupo Manoel Philomeno</span> 
        <br>
        <b>Estudo das obras  de Manoel Philomeno de Miranda</b>
    </div>
    <br>
    
    
    <!-- programação -->
    <div>
        <table>
            <thead>
                <th>Local</th>
                <th>Conteúdo</th>
                <th>Horário</th>
            </thead>
            <tbody>
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Sábado - (quinzenalmente,1°, 3° e 5º sábados)</td>
                </tr>
                <tr>
                    <td>Chico Xavier</td>
                    <td>Livro "Trilhas da Libertação"</td>
                    <td>18:30h às 19:30h</td>
                </tr> 
            </tbody>
        </table>
    </div>
    
    <br>
    <hr>
    <br>
        
    <div class="txt_esde">
        <span class="destaque">Grupo Plenitude</span> 
        <br>
        <b>Estudo do livro "Plenitude" de Divaldo Franco / Joanna de Ângelis</b>
    </div>
    <br>
    
    <!-- programação -->
    <div>
        <table>
            <thead>
                <th>Local</th>
                <th>Conteúdo</th>
                <th>Horário</th>
            </thead>
            <tbody>
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Sábado - (quinzenalmente,1°, 3° e 5º sábados)</td>
                </tr>
                <tr>
                    <td>Chico Xavier</td>
                    <td>Livro "Plenitude"</td>
                    <td>18h às 19h</td>
                </tr> 
            </tbody>
        </table>
    </div>
    
    <br>
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Pré-requisitos</span>
        <br>
        <ul>
            <li>ter cursado o ESDE.</li>
        </ul> 
    </div>
</div>