<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Grupo Joanna</span> 
        <br>
        <b>Estudo da Série Psicológica de Joanna de Ângelis</b>
    </div>
    <!-- programação -->
    <div>
        <p>
            <span class="boldit">Sábado</span> (quinzenalmente, 2° e 4° sábados) - 18:30h às 19:30h<br>
            Sala Bezerra de Menezes
        </p>
    </div>
    
    
    <div>
        <p>
            
        </p>
    </div>
    
    <div class="txt_esde">
        <span class="destaque">Grupo Manoel Philomeno</span> 
        <br>
        <b>Estudo das obras  de Manoel Philomeno de Miranda</b>
    </div>
    
    <!-- programação -->
    <div>
        <p>
            <span class="boldit">Sábado</span> (quinzenalmente, 1° e 3 sábados) - 18:30h às 19:30h<br>
            Sala Chico Xavier
        </p>
    </div>
    
    <br>
    
    <!-- Conteúdo Programático -->
    <div>
        <span class="destaque">Conteúdo Programático</span>
        <br>
        <b>Grupo Joanna: Mansão do Caminho – BA</b>
    </div>
    
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Pré-requisitos</span>
        <br>
        <ul>
            <li>ter cursado o ESDE.</li>
        </ul> 
    </div>
</div>