<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">ESDE</span> 
        <br>
        <b>Estudo Sistematizado da Doutrina Espírita</b>
    </div>
    <!-- programação ESDE -->
    <div>
        <p>
            <span class="boldit">Segunda-feira</span> - De 16:00h às 17:00h<br>
            Salão
        </p>

        <p>
            <span class="boldit">Terça-feira</span> - De 18:45h às 20:00h<br>
            Sala Chico Xavier
        </p>

        <p>
            <span class="boldit">Sábado</span> (1°, 3° e 5° sábados) - De 18:30h às 20:00h<br>
            Sala Bezerra de Menezes
        </p>
    </div>
    
    <div class="txt_eade">
        <span class="destaque">EADE</span>
        <br>
        <b>Estudo Aprofundado da Doutrina Espírita</b>
    </div>
    <!-- Programação EADE -->
    <div>
        <p>
            <span class="boldit">Sábado</span> - De 16:30h às 18:00h<br>
            Sala Chico Xavier
        </p>
    </div>    
    
    <br>
    
    <!-- Conteúdo Programático -->
    <div>
        <span class="destaque">Conteúdo Programático</span>
        <br>
        <b>Apostilas da FEB</b> - Federação Espírita Brasileira
    </div>
    <div>
        <p>
            <span class="boldit">OBS</span>: Como alternativa ao ESDE temos o estudo sistemático do Livro dos Espíritos, Sextas-feiras 19h30min
        </p>
    </div>
    
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Pré-requisitos</span>
        <br>
        <ul>
            <li>Vaga na turma;</li>
            <li>frequencia ao CEI;</li>
            <li>aprovação da ficha de inscrição pela coordenação do ESDE.</li>
        </ul> 
    </div>
</div> <!-- end div ESDE -->
