
    <blockquote>
        <p class="lead">ESDE - Estudo Sistematizado da Doutrina Espírita</p>
    </blockquote>

    <!-- programação ESDE -->
    <div>
        <table class="table table-bordered">
            <thead>
                <th class="info">Local</th>
                <th class="info">Conteúdo</th>
                <th class="info">Horário</th>
            </thead>
            <tbody>
                <!-- SEGUNDA -->
                <tr>
                    <td colspan="3" class="semana_td">Segunda-feira</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Yvonne do Amaral Pereira (Dramas da Obsessão)</td>
                    <td>16h as 17h</td>
                </tr>
                
                <!-- TERÇA -->
                <tr>
                    <td colspan="3" class="semana_td">Terça-feira</td>
                </tr>
                <tr>
                    <td>Chico Xavier</td>
                    <td>Apostilas da FEB</td>
                    <td>18:45h as 20h</td>
                </tr>
                <tr>
                    <td>Joanna de Ângelis</td>
                    <td>O que é o Espiritismo</td>
                    <td>19h as 20h</td>
                </tr>
                
                <!-- SEXTA -->
                <tr>
                    <td colspan="3" class="semana_td">Sexta-feira</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Yvonne do Amaral Pereira (Ressureição e Vida)</td>
                    <td>18h as 19h</td>
                </tr>
                
                <!-- SÁBADOS -->
                <tr>
                    <td colspan="3" class="semana_td">Sábado  (1°, 3° e 5° sábados)</td>
                </tr>
                <tr>
                    <td>Bezerra de Menezes</td>
                    <td>Apostilas da FEB</td>
                    <td>18:30h as 20h</td>
                </tr>
            </tbody>
        </table>
    </div>   
    
    <h4 class="bg-primary">
        Pré-requisitos
    </h4>
    
    <div>
        <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Vaga na turma</p>
        <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Frequencia ao CEI</p>
        <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Aprovação da ficha de inscrição pela coordenação do ESDE</p>
    </div>
