<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">ESDE</span> 
        <br>
        <b>Estudo Sistematizado da Doutrina Espírita</b>
    </div>
    <!-- programação ESDE -->
    <div>
        <table>
            <thead>
                <th>Local</th>
                <th>Conteúdo</th>
                <th>Horário</th>
            </thead>
            <tbody>
                <!-- SEGUNDA -->
                <tr>
                    <td colspan="3" class="semana_td">Segunda-feira</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Yvonne do Amaral Pereira (Dramas da Obsessão)</td>
                    <td>16h as 17h</td>
                </tr>
                
                <!-- TERÇA -->
                <tr>
                    <td colspan="3" class="semana_td">Terça-feira</td>
                </tr>
                <tr>
                    <td>Chico Xavier</td>
                    <td>Apostilas da FEB</td>
                    <td>18:45h as 20h</td>
                </tr>
                <tr>
                    <td>Joanna de Ângelis</td>
                    <td>O que é o Espiritismo</td>
                    <td>19h as 20h</td>
                </tr>
                
                <!-- SEXTA -->
                <tr>
                    <td colspan="3" class="semana_td">Sexta-feira</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Yvonne do Amaral Pereira (Ressureição e Vida)</td>
                    <td>18h as 19h</td>
                </tr>
                
                <!-- SÁBADOS -->
                <tr>
                    <td colspan="3" class="semana_td">Sábado  (1°, 3° e 5° sábados)</td>
                </tr>
                <tr>
                    <td>Bezerra de Menezes</td>
                    <td>Apostilas da FEB</td>
                    <td>18:30h as 20h</td>
                </tr>
            </tbody>
        </table>
        
        
        
<!--        <p>
            <span class="boldit">Segunda-feira</span> - De 16:00h às 17:00h<br>
            Salão
        </p>

        <p>
            <span class="boldit">Terça-feira</span> - De 18:45h às 20:00h<br>
            Sala Chico Xavier
        </p>
        
         <p>
            <span class="boldit">Terça-feira</span> - De 19:00h às 20:00h<br>
            Sala Joanna de Ângelis (O que é o Espiritismo)
        </p>
        
         SEXTA 
        <p>
            <span class="boldit">Sexta-feira</span> - De 18:00h às 19:00h<br>
            Sala Chico Xavier
        </p>

        <p>
            <span class="boldit">Sábado</span> (1°, 3° e 5° sábados) - De 18:30h às 20:00h<br>
            Sala Bezerra de Menezes
        </p>-->
    </div>    
    
    
    <!-- Conteúdo Programático -->
<!--    <div>
        <span class="destaque">Conteúdo Programático</span>
        <br>
        <b>Apostilas da FEB</b> - Federação Espírita Brasileira
        <br>
        <b>Obras Básicas</b>
        <br>
        <b>Obra de Yvonne do Amaral Pereira</b>
    </div>-->
        
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Pré-requisitos</span>
        <br>
        <ul>
            <li>Vaga na turma;</li>
            <li>frequencia ao CEI;</li>
            <li>aprovação da ficha de inscrição pela coordenação do ESDE.</li>
        </ul> 
    </div>
</div> <!-- end div ESDE -->
