<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Escola de Evangelho Iacy</span> 
        <br>
        <b>(Setor de Infância da Área de Evangelização da Família)</b> - Foi criada em 12 de junho de 1949, com o 
        objetivo de levar às crianças lições sobre o evangelho à luz da doutrina espírita. Segue a 
        orientação da Federação Espírita Brasileira (FEB), sendo que o material didático é elaborado pelos 
        evangelizadores, os quais planejam os encontros, de acordo com a faixa etária de cada turma.
    </div>
    <div class="txt_artigo">
        <span class="destaque">Mocidade Espírita João Marcos</span> 
        <br>
        <b>(Setor de Juventude do Departamento de Infância e Juventude do CEI )</b> - Foi fundada em 12 de junho 
        de 1956, com o objetivo de conduzir o jovem à compreensão de sua responsabilidade como um ser 
        encarnado em evolução. Sua finalidade é a evolução espírita do jovem, sendo orientada por programa 
        estabelecido pela Federação Espírita Brasileira (FEB) e complementada por programa específico, 
        elaborado a partir de sugestões e necessidades do grupo.
    </div>
    
    <br>    
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Faixa Etária</span>
        <br>
        <ul>
            <li><span class="boldit">Ciclinho (maternal)</span> - até 2 anos;</li>
            <li><span class="boldit">1° Ciclo de infancia</span> - 3 a 5 anos;</li>
            <li><span class="boldit">2° Ciclo de infância</span> - 6 a 8 anos;</li>
            <li><span class="boldit">3° Ciclo de infância</span> - 9 a 10 anos;</li>
            <li><span class="boldit">1° Ciclo de juventude</span> - 11 a 12 anos;</li>
            <li><span class="boldit">2° Ciclo de juventude</span> - 13 a 14 anos;</li>
            <li><span class="boldit">3° Ciclo de juventude</span> - 15 a 17 anos;</li>
            <li><span class="boldit">4° Ciclo de juventude</span> - 18 a 25 anos;</li>
            <li><span class="boldit">Família</span> - pais e responsáveis pelas crianças e jovens da evangelização.</li>
        </ul> 
    </div>
</div>













