    <blockquote>
        <p class="lead">Grupo de Pais Nancy Leite de Araújo
        <small>Serviço de Evangelização da Família da Área de Evangelização da Família</small></p>
    </blockquote> 

<div>
    <p class="lead">Fundado em 1992, recebendo esta denominação como lembrança à irmã que fundou e presidiu o 
        <span class="text-primary">CEI</span> durante 52 anos de sua vida e desencarnou em 19 de Julho de 1992.
    Este grupo já se reunia aos domingos desde 1989, com os pais das crianças, estudando temas ligados à educação
    dos filhos e relações familiares, com base na Doutrina Espírita. Trabalho este iniciado e acompanhado  pelos 
    irmãos Fasuto José Peluso e Neuza Azevedo Peluso, até desencarnarem em 2002 e 2011, respectivamente.</p>
</div>


    <!-- Horários -->
    <div>
        <!--<h4 class="bg-primary">Horários</h4>-->
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Sábados</b> - 16:00h às 17:45h</p>
    </div>
    
   
    
    <!-- Pré-requisitos -->
    <div>
        <h4 class="bg-primary">Faixa Etária</h4>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>Família</b> - pais e responsáveis pelas crianças e jovens da evangelização</p>            
    </div>
