<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Evangelização da Família</span> 
        <br>
        <b>(Serviço de Evangelização da família da Área de Evangelização da Família)</b>
    </div>
    
    <br>    
    
    
    <!-- Horários -->
    <div>
        <span class="destaque">Horários</span>
        <br>
        <b>Sábados</b> - 16:00h às 17:45h
    </div>
    
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Faixa Etária</span>
        <br>
        <ul>
            <li><span class="boldit">Família</span> - pais e responsáveis pelas crianças e jovens da evangelização.</li>
        </ul> 
    </div>
</div>