    <blockquote>
        <p class="lead">Evangelização da Família
        <small>Serviço de Evangelização da Família da Área de Evangelização da Família</small></p>
    </blockquote> 


    <!-- Horários -->
    <div>
        <!--<h4 class="bg-primary">Horários</h4>-->
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Sábados</b> - 16:00h às 17:45h</p>
    </div>
    
   
    
    <!-- Pré-requisitos -->
    <div>
        <h4 class="bg-primary">Faixa Etária</h4>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>Família</b> - pais e responsáveis pelas crianças e jovens da evangelização</p>            
    </div>
