<div id="artigo" style="margin-top: 10px;">
<span class="destaque">Origem</span><br>
<p>Num grupo familiar, em Vila Isabel, <font class="destaq">IBIRAJARA</font>, o Mentor Espiritual do <font class="destaq">CEI</font>, deu suas primeiras comunicações
mediúnicas pela médium Vicentina Bruno, em 1928. A Entidade, altamente evoluída, mostrou profundidade em
seus conceitos e sublimidade em suas concepções.
</p>
<p>Em 1932, na residência da família Bruno, à rua Bela Vista,143 - Engenho Novo, estenderam-se as atividades do grupo, ainda sob o mesmo cunho familiar. <font class="destaq">IBIRAJARA</font> iniciou a tarefa de
promover o preparo de vários médiuns, ao mesmo tempo que, no plano espiritual, entidades esclarecidas
pelo inesquecível Mentor, organizavam-se em falanges diversas que passariam a operar sob sua orientação
sábia e justa.</p><br>
<span class="destaque">Fundação</span>
<p>Obedecendo à direção lúcida desse Benfeitor amado, o grupo espírita, a 6 de agosto de 1940, define-se como
sociedade religiosa, oficialmente reconhecida, passando a denominar-se
<font class="destaq">"CENTRO ESPÍRITA IBIRAJARA"</font>. A 8 de
dezembro de 1940 realizou-se a primeira reunião pública, no prédio da rua Teodoro da Silva, 453, em Vila
Isabel.</p><br>
<span class="destaque">Enfoques sobre IBIRAJARA</span>
<p>Segundo revelação feita por Francisco Cândido Xavier, numa visita de membros do CEI a Pedro Leopoldo,
em 1952, <font class="destaq">IBIRAJARA</font> há mais ou menos 200 anos a.C. viveu em Atenas; foi
Protinus, sendo conhecido como filósofo dos humildes. Entretanto, preferiu sempre ocultar sua
cultura, expressando uma linguagem simples e modesta que, não obstante, refletia a sua verdadeira
hierarquia espiritual.</p>
<p>Através da médium, <font class="destaq">IBIRAJARA</font> referiu-se às suas duas últimas reencarnações,
ocorridas em território brasileiro como silvícola, conforme pedido que fizera a JESUS, para traçar
normas de evolução e progresso entre os indígenas e despedir-se das lides humanas com esse trabalho
que significava seu grande carinho pelas almas simples e humildes. Revelou, ainda, que na última
passagem pelo nosso planeta foi pajé de uma tribo do Amazonas, tendo desencarnado, já idoso,
na primeira década do século XIX.</p>
<p>Acenava, ainda, aos médiuns por ele orientados, com um futuro de muito trabalho no campo social,
onde o sentido de caridade seria amplamente exemplificado. Falava num lar - o
<font class="destaq">LAR DE IBIRAJARA</font> - onde crianças, jovens, adultos e idosos
encontrariam socorro e amparo para suas dificuldades. Para os que o ouviam, na época, esse
programa parecia um sonho que só remotamente poderia se realizar. Ele, porém, sabia o que estava dizendo.</p>
<p>No dia 12 de junho de 1945, em memorável reunião realizada na sede provisória do
<font class="destaq">CEI</font>, à rua Barão de Cotegipe, nº 209 - térreo, após um convívio
inesquecível de 17 anos, obedecendo a determinações espirituais, <font class="destaq">IBIRAJARA</font>
despediu-se de seus amigos na Terra e partiu para regiões superiores.</p><br>
<span class="destaque">Sedes do CEI</span>
<p>A primeira Sede, quando da instalação oficial do Centro, em 1940, situava-se na rua Teodoro da
Silva nº 453, em Vila Isabel.</p>
<p>Em junho de 1945, transferiu-se para o prédio da rua Barão de Cotegipe nº 209 - térreo, no mesmo bairro.</p>
<p>Em agosto de 1947, passou a funcionar na Av. Paula e Souza nº 134 - térreo, Maracanã, de onde mudou-se em fevereiro de 1950 para a rua dos Artistas nº 151, cedido por gentileza dos confrades
do Grupo Espírita Discípulos de Samuel que aí funciona até hoje.</p>
<p>Essas mudanças sucessivas retratam as dificuldades imensas enfrentadas pela Família de <font class="destaq">IBIRAJARA </font>para que o seu núcleo de trabalho permanecesse ativo,
cumprindo os objetivos traçados pelo seu mentor espiritual.</p>
<p>Em 1950, porém numa resposta positiva à resistência e idealismo dos membros responsáveis pelo <font class="destaq">CEI</font>, surge a possibilidade de aquisição do prédio próprio no
endereço atual, rua Barão de São Francisco nº 156, bairro do Andaraí.</p>
<p>De início era uma casa simples, baixa, frente de rua. Graças aos esforços da Diretoria e amigos incansáveis, hoje, esta Casa Espírita tem condições físicas que correspondem às múltiplas atividades aqui desenvolvidas.</p>
</div>