
    <blockquote>
        <p class="lead">Escola de Evangelho Iacy
        <small>Serviço de Evangelização da Infância da Área de Evangelização da Família</small></p>
    </blockquote> 


    <div>
        <p class="lead">Foi criada em 12 de junho de 1949, com o 
        objetivo de levar às crianças lições sobre o evangelho à luz da doutrina espírita. Segue a 
        orientação da Federação Espírita Brasileira (FEB), sendo que o material didático é elaborado pelos 
        evangelizadores, os quais planejam os encontros, de acordo com a faixa etária de cada turma.</p>
    </div>    
    
    <!-- Horários -->
    <div>
        <!--<h4 class="bg-primary">Horários</h4>-->
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Sábados</b> - 16:00h às 17:45h</p>
    </div>
    
   
    
    <!-- Pré-requisitos -->
    <div>
        <h4 class="bg-primary">Faixa Etária</h4>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>Berçário</b> - até 2 anos</p>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>1° Ciclo de infancia</b> - 3 a 5 anos</p>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>2° Ciclo de infância</b> - 6 a 8 anos</p>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>3° Ciclo de infância</b> - 9 a 10 anos</p>        
    </div>