<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Escola de Evangelho Iacy</span> 
        <br>
        <b>(Setor de Infância da Área de Evangelização da Família)</b> - Foi criada em 12 de junho de 1949, com o 
        objetivo de levar às crianças lições sobre o evangelho à luz da doutrina espírita. Segue a 
        orientação da Federação Espírita Brasileira (FEB), sendo que o material didático é elaborado pelos 
        evangelizadores, os quais planejam os encontros, de acordo com a faixa etária de cada turma.
    </div>
    
    <br>    
    
    
    <!-- Horários -->
    <div>
        <span class="destaque">Horários</span>
        <br>
        <b>Sábados</b> - 16:00h às 17:45h
    </div>
    
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Faixa Etária</span>
        <br>
        <ul>
            <li><span class="boldit">Ciclinho (maternal)</span> - até 2 anos;</li>
            <li><span class="boldit">1° Ciclo de infancia</span> - 3 a 5 anos;</li>
            <li><span class="boldit">2° Ciclo de infância</span> - 6 a 8 anos;</li>
            <li><span class="boldit">3° Ciclo de infância</span> - 9 a 10 anos.</li>
        </ul> 
    </div>
</div>