    <!-- JAVASCRIPT -->
    <script type="text/javascript" src="includes/js/jquery.js"></script>
    <script type="text/javascript" src="includes/js/jquery-ui.js"></script>
    <script type="text/javascript" src="includes/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="system/jquery/jquery.reveal.js"></script>
    <script type="text/javascript" src="system/jquery/maskedinput.js"></script>
    <script type="text/javascript" src="system/jquery/geral.js"></script>
    <script type="text/javascript" src="template/jquery/jquery-easing-compatibility.1.2.pack.js"></script>
    <script type="text/javascript" src="template/jquery/coda-slider.1.1.1.pack.js"></script>
    <script type="text/javascript" src="template/jquery/slider.js"></script>
    <script type="text/javascript" src="includes/js/<?php echo $controller ?>.js"></script>

    <!-- Importa os arquivos CSS -->
    <link href="includes/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="includes/css/geral.css" rel="stylesheet" type="text/css" />
    <!--<link href="template/css/MenuPrincipalCss.css" rel="stylesheet" type="text/css" />-->
    <link href="template/css/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="template/css/smoothness/reveal.css" rel="stylesheet" type="text/css" />
    <link href="template/css/<?php echo $controller ?>.css" rel="stylesheet" type="text/css" />



