<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Grupo Amália Domingo Soler</span> 
        <br>
        <b>Estudo e Prática da Mediunidade</b>
    </div>
    <!-- programação -->
    <div>
        <p>
            <span class="boldit">Terça-feira</span> - De 18:45h às 20:00h<br>
            Sala Joanna de Angelis
        </p>
    </div>
    <br>
    
    <!-- Conteúdo Programático -->
    <div>
        <span class="destaque">Conteúdo Programático</span>
        <br>
        <b>Obras de Allan Kardec e André Luis </b>
    </div>
    <div>
        <p>
            
        </p>
    </div>
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Pré-requisitos</span>
        <br>
        <ul>
            <li>ter cursado o ESDE;</li>
            <li>frequencia ao CEI;</li>
            <li>tempo mínimo de frequência no CEI;</li>
            <li>aprovação da ficha de inscrição pela coordenação do ESDE.</li>
        </ul> 
    </div>
</div>