    <blockquote>
        <p class="lead">Grupo Leon Denis
        <small>Estudo e Prática da Mediunidade</small></p>
    </blockquote>


    <div>
        <table class="table table-bordered">
            <thead>
                <th class="info">Local</th>
                <th class="info">Conteúdo</th>
                <th class="info">Horário</th>
            </thead>
            <tbody>
                <!-- TERÇA -->
                <tr>
                    <td colspan="3" class="semana_td">Terça-feira</td>
                </tr>
                <tr>
                    <td>Joanna de Ângelis</td>
                    <td>Apostila da FEB (Tomo II)</td>
                    <td>18:45h às 20h</td>
                </tr>  
            </tbody>
        </table>
    </div>
    

    <blockquote>
        <p class="lead">Grupo de Estudos Asdrubal
        <small>Estudo e Prática da Mediunidade (para os Médiuns)</small></p>
    </blockquote>
    
    <!-- programação -->
    <div>
        <table class="table table-bordered">
            <thead>
                <th class="info">Local</th>
                <th class="info">Conteúdo</th>
                <th class="info">Horário</th>
            </thead>
            <tbody>
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Quinta-feira</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Série André Luis / Obras Básicas</td>
                    <td>18:45h às 19:35h</td>
                </tr>  
                
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Quinta-feira (Primeira do Mês)</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Série André Luis / Obras Básicas</td>
                    <td>19:50h às 21h</td>
                </tr>  
            </tbody>
        </table>
    </div>
    
        
    <!-- Pré-requisitos -->
    <div>
        <h4 class="bg-primary">Pré-requisitos</h4>
            <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Ter cursado o ESDE</p>
            <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Frequencia ao CEI</p>
            <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Tempo mínimo de frequência no CEI</p>
            <p><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> Aprovação da ficha de inscrição pela coordenação do ESDE</p>        
    </div>