<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Grupo Leon Denis</span> 
        <br>
        <b>Estudo e Prática da Mediunidade</b>
    </div>
    <!-- programação -->
    <div>
        <table>
            <thead>
                <th>Local</th>
                <th>Conteúdo</th>
                <th>Horário</th>
            </thead>
            <tbody>
                <!-- TERÇA -->
                <tr>
                    <td colspan="3" class="semana_td">Terça-feira</td>
                </tr>
                <tr>
                    <td>Joanna de Ângelis</td>
                    <td>Apostila da FEB (Tomo II)</td>
                    <td>18:45h às 20h</td>
                </tr>                
                
            </tbody>
        </table>
    </div>
    <br>    
    
    <div class="txt_artigo">
        <span class="destaque">Grupo de Estudos Asdrubal</span> 
        <br>
        <b>Estudo e Prática da Mediunidade (para os Médiuns)</b>
    </div>
    <!-- programação -->
    <div>
        <table>
            <thead>
                <th>Local</th>
                <th>Conteúdo</th>
                <th>Horário</th>
            </thead>
            <tbody>
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Quinta-feira</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Série André Luis / Obras Básicas</td>
                    <td>18:45h às 19:35h</td>
                </tr>  
                
                <!-- QUINTA -->
                <tr>
                    <td colspan="3" class="semana_td">Quinta-feira (Primeira do Mês)</td>
                </tr>
                <tr>
                    <td>Salão</td>
                    <td>Série André Luis / Obras Básicas</td>
                    <td>19:50h às 21h</td>
                </tr>  
                
            </tbody>
        </table>
    </div>
    <br>    
    
        
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Pré-requisitos</span>
        <br>
        <ul>
            <li>ter cursado o ESDE;</li>
            <li>frequencia ao CEI;</li>
            <li>tempo mínimo de frequência no CEI;</li>
            <li>aprovação da ficha de inscrição pela coordenação do ESDE.</li>
        </ul> 
    </div>
</div>