<div id="nav">
    <ul class="box">
        <li><a href="index">Home</a></li>
        <li><a href="programacao" title="Reuniões Públicas">Programação</a></li> <!-- Active page (highlighted) -->
        <li><a href="#">Estudos</a>
            <ul>
                <li><a href="artigo/exibe/esde">ESDE</a></li>
                <li><a href="artigo/exibe/mediunidade">Mediunidade</a></li>
                <li><a href="artigo/exibe/complementares"><span style="font-size: 14px;">Obras Complementares</span></a></li>
            </ul>
        </li>
        <li>
            <a href="#">Evangelização</a>
            <ul>
                <li><a href="artigo/exibe/infantil">Infantil</a></li>
                <li><a href="artigo/exibe/mocidade">Mocidade</a></li>
                <li><a href="artigo/exibe/familia">Família</a></li>
            </ul>
        </li>
        <li><a href="eventos">Eventos</a></li>
        <li><a href="contato">Contato</a></li>
    </ul>
</div>