<div id="nav">
    <ul class="box">
        <li><a href="<?=DIR ?>index">Home</a></li>
        <li><a href="<?=DIR ?>programacao" title="Reuniões Públicas">Programação</a></li> <!-- Active page (highlighted) -->
        <li><a href="#">Estudos</a>
            <ul>
                <li><a href="<?=DIR ?>artigo/exibe/sessao/esde">ESDE</a></li>
                <li><a href="<?=DIR ?>artigo/exibe/sessao/mediunidade">Mediunidade</a></li>
                <li><a href="<?=DIR ?>artigo/exibe/sessao/complementares"><span style="font-size: 14px;">Obras Complementares</span></a></li>
            </ul>
        </li>
        <li>
            <a href="#">Evangelização</a>
            <ul>
                <li><a href="<?=DIR ?>artigo/exibe/sessao/infantil">Infantil</a></li>
                <li><a href="<?=DIR ?>artigo/exibe/sessao/mocidade">Mocidade</a></li>
                <li><a href="<?=DIR ?>artigo/exibe/sessao/familia">Família</a></li>
            </ul>
        </li>
        <li><a href="#">Eventos</a></li>
        <li><a href="<?=DIR ?>contato">Contato</a></li>
    </ul>
</div>