
    <blockquote>
        <p class="lead">Mocidade Espírita João Marcos
        <small>Serviço de Evangelização da Juventude da Área de Evangelização da Família</small></p>
    </blockquote> 


    <div>
        <p class="lead">Foi fundada em 12 de junho 
        de 1956, com o objetivo de conduzir o jovem à compreensão de sua responsabilidade como um ser 
        encarnado em evolução. Sua finalidade é a evolução espírita do jovem, sendo orientada por programa 
        estabelecido pela Federação Espírita Brasileira (FEB) e complementada por programa específico, 
        elaborado a partir de sugestões e necessidades do grupo.</p>
    </div>    

    <!-- Horários -->
    <div>
        <!--<h4 class="bg-primary">Horários</h4>-->
        <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Sábados</b> - 16:00h às 18:00h</p>
    </div>
    
    
    <!-- Pré-requisitos -->
    <div>
        <h4 class="bg-primary">Faixa Etária</h4>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>1° Ciclo de juventude</b> - 11 a 12 anos</p>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>2° Ciclo de juventude</b> - 13 a 14 anos</p>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>3° Ciclo de juventude</b> - 15 a 17 anos</p>
            <p><span class="glyphicon glyphicon-arrow-right text-primary" aria-hidden="true"></span> <b>4° Ciclo de juventude</b> - 18 a 25 anos</p>        
    </div>