<div id="artigo">
    <div class="txt_artigo">
        <span class="destaque">Mocidade Espírita João Marcos</span> 
        <br>
        <b>(Setor de Juventude do Departamento de Infância e Juventude do CEI )</b> - Foi fundada em 12 de junho 
        de 1956, com o objetivo de conduzir o jovem à compreensão de sua responsabilidade como um ser 
        encarnado em evolução. Sua finalidade é a evolução espírita do jovem, sendo orientada por programa 
        estabelecido pela Federação Espírita Brasileira (FEB) e complementada por programa específico, 
        elaborado a partir de sugestões e necessidades do grupo.
    </div>
    
    <br>    
    
    
    <!-- Horários -->
    <div>
        <span class="destaque">Horários</span>
        <br>
        <b>Sábados</b> - 16:00h às 18:00h
    </div>
    
    <br>
    
    <!-- Pré-requisitos -->
    <div>
        <span class="destaque">Faixa Etária</span>
        <br>
        <ul>
            <li><span class="boldit">1° Ciclo de juventude</span> - 11 a 12 anos;</li>
            <li><span class="boldit">2° Ciclo de juventude</span> - 13 a 14 anos;</li>
            <li><span class="boldit">3° Ciclo de juventude</span> - 15 a 17 anos;</li>
            <li><span class="boldit">4° Ciclo de juventude</span> - 18 a 25 anos.</li>
        </ul> 
    </div>
</div>