<div id="prog_semana">
    <div class="TabControl">
        <div id="header">
            <ul class="abas">
            <?php
                foreach ($texto as $programa)
                { 
                    
                    $d = date('w', strtotime($programa['data']));
                    
                    switch ($d)
                    {
                        case 1:
                            $dia = "Segunda";
                            $horario = '15h';
                            break;
                        case 2:
                            $dia = "Terça";
                            $horario = '20:10h';
                            break;
                        case 3:
                            $dia = 'Quarta';
                            $horario = '19:30h';
                            break;
                        case 5:
                            $dia = 'Sexta';
                            $horario = '19:30h';
                            break;
                        case 6:
                            $dia = 'Sábado';
                            $horario = '19:45h';
                            break;
                    }
                    
                    
                    
                    
                    ?>
                <li>
                    <div class="aba">
                        <span><?php echo $dia; ?></span>
                        <br>
                        <span class="cit"><?php echo $horario; ?></span>
                    </div>
                </li>
            
                <?php } ?>
            
                
<!--                <li>
                    <div class="aba">
                        <span>Terça</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Quarta</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Sexta</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Sábado</span>
                    </div>
                </li>-->
            </ul>
        </div>
        <div id="content_aba">
            <?php
                foreach ($texto as $programa)
                { ?>
                    <div class="conteudo_aba">  
                        <!-- Dia -->
                        <p class="dtPalestra">
                           <?php
                            $data = new TDate($programa['data']);
                            echo $data->getDataExtenso();
                            
                            // Pega o dia da semana
                            //$diasemana = date('w', strtotime($programa['data']));
                           ?>
                        </p>                           
                        <!-- Tema -->
                        <p style="margin-top:15px">
                            <span class="tema">
                                <span style="color: #006; font-weight: bold;">Tema:</span>
                                <?php echo $programa['tema']; ?> 
                                <span class="cit">(<?php echo $programa['subsidio']; ?>)</span>
                            </span>
                        </p>
                        <!-- Expositor -->
                        <p style="margin-top:15px">
                            <span class="expositor">
                                <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programa['expositor']; ?>
                            </span>
                        </p>
                    </div> <?php
                }
            ?>
    </div>
</div>
</div> <!-- end Programação Semana -->