<div id="prog_semana">
    <div class="TabControl">
        <div id="header">
            <ul class="abas">
                <li>
                    <div class="aba">
                        <span>Segunda</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Terça</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Quarta</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Sexta</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Sábado</span>
                    </div>
                </li>
            </ul>
        </div>
        <div id="content_aba">
            <div class="conteudo_aba">                             
                <!-- Dia -->
                <p class="dtPalestra">
                   07 de Agosto de 2014
                </p>                           
                <!-- Tema -->
                <p style="margin-top:15px">
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        "A dissertação inacabada" 
                        <span class="cit">(No Roteiro de Jesus, Gerson S. Monteiro, cap 32)</span>
                    </span>
                </p>
                <!-- Expositor -->
                <p style="margin-top:15px">
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> Denise Delgado
                    </span>
                </p>
            </div>
            <div class="conteudo_aba">
                <!-- Dia -->
                <p class="dtPalestra">
                   14 de Agosto de 2014
                </p>                           
                <!-- Tema -->
                <p style="margin-top:15px">
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        "O egoísmo"
                        <span class="cit">(cap. XI, itens 11 e 12)</span>
                    </span>
                </p>
                <!-- Expositor -->
                <p style="margin-top:15px">
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> Lilian Souza (AE Izabel)
                    </span>
                </p>
            </div>
            <div class="conteudo_aba">
                <!-- Dia -->
                <p class="dtPalestra">
                   14 de Agosto de 2014
                </p> 
                Conteúdo da aba 3
            </div>
            <div class="conteudo_aba">
                <!-- Dia -->
                <p class="dtPalestra">
                   14 de Agosto de 2014
                </p> 
                Conteúdo da aba 4
            </div>
            <div class="conteudo_aba">
                <!-- Dia -->
                <p class="dtPalestra" style="display: block;">
                   14 de Agosto de 2014
                </p> 
                Conteúdo da aba 5
            </div>
        </div>
    </div>
</div>