<?php
    foreach ($texto as $programa)
    {
        // Pega o dia da semana
        $d = date('w', strtotime($programa['data']));
        
        $dtProg[$d]['data'] = $programa['data'];
        $dtProg[$d]['tema'] = $programa['tema'];
        $dtProg[$d]['subsidio'] = $programa['subsidio'];
        $dtProg[$d]['expositor'] = $programa['expositor'];
        
        ksort($dtProg);
        
        //print_r($dtProg);
    }
    







?>

<div id="prog_semana">
    <div class="TabControl">
        <div id="header">
            <ul class="abas">
                <li>
                    <div class="aba">
                        <span>Segunda</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Terça</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Quarta</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Sexta</span>
                    </div>
                </li>
                <li>
                    <div class="aba">
                        <span>Sábado</span>
                    </div>
                </li>
            </ul>
        </div>
        <div id="content_aba">
            <?php
                foreach ($dtProg as $programa)
                { ?>
                    <div class="conteudo_aba">  
                        <!-- Dia -->
                        <p class="dtPalestra">
                           <?php
                            $data = new TDate($programa['data']);
                            echo $data->getDataExtenso();
                            
                            // Pega o dia da semana
                            //$diasemana = date('w', strtotime($programa['data']));
                           ?>
                        </p>                           
                        <!-- Tema -->
                        <p style="margin-top:15px">
                            <span class="tema">
                                <span style="color: #006; font-weight: bold;">Tema:</span>
                                <?php echo $programa['tema']; ?> 
                                <span class="cit">(<?php echo $programa['subsidio']; ?>)</span>
                            </span>
                        </p>
                        <!-- Expositor -->
                        <p style="margin-top:15px">
                            <span class="expositor">
                                <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programa['expositor']; ?>
                            </span>
                        </p>
                    </div> <?php
                }
            ?>
    </div>
</div>
</div> <!-- end Programação Semana -->