<!-- SLIDESHOW -->
<div class="row">
    <div id="" class="col-md-12">
        <!-- CAROUSEL -->
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <!--<li data-target="#carousel-example-generic" data-slide-to="2" ></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>-->
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
              
            <div class="item active wrapper">
                <img src="template/images/slideshow/campanha-evangelizacao-da-familia.png" alt="..." class="center-block">
                <input type="hidden" name="arquivo" value="campanha-evangelizacao-da-familia">
            </div>
              
<!--            <div class="item wrapper">
                <img src="template/images/slideshow/homenagem-a-kardec.jpg" alt="..." class="center-block">
                <input type="hidden" name="arquivo" value="homenagem-a-kardec">
            </div>  -->
              
            <div class="item wrapper">
                <img src="template/images/slideshow/introducao-ao-espiritismo.jpg" alt="..." class="center-block">
                <input type="hidden" name="arquivo" value="#">
            </div>  
              
            

            <!-- BANNER EMPADÃO -->
<!--            <div class="item wrapper">
                <img src="template/images/slideshow/banner-empadao.jpg" alt="..." class="center-block">
                <input type="hidden" name="arquivo" value="#">
            </div>

            <div class="item wrapper">
                <img src="template/images/slideshow/reuniao-comemorativa-75-anos-cei.png" alt="..." class="center-block">
                <input type="hidden" name="arquivo" value="reuniao-comemorativa-75-anos-cei">
            </div>-->
              
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div>  
</div>
