<div class="slider-wrap">
    <div id="main-photo-slider" class="csw">
        <div class="panelContainer">
            <!-- EVENTO 01 -->
<!--            <div class="panel" title="Panel 1">
                <div class="wrapper">
                     IMAGEM 
                    <img src="template/images/slideshow/seminario-ansiedade-depressao.jpg" alt="temp" />
                     DIZER 
                    <div class="photo-meta-data">
                        Homenagem a Kardec<br />
                        <span>Dia 03 de Outubro a partir das 19:30h</span>
                    </div>
                    <input type="hidden" name="ano" value="2014">
                    <input type="hidden" name="arquivo" value="seminario-ansiedade-depressao">
                </div>
            </div>-->
            
            <!--EVENTO 02--> 
            <div class="panel" title="Panel 1">
                <div class="wrapper">
                    <img src="template/images/slideshow/banner empadao.jpg" alt="temp" />
                    <input type="hidden" name="ano" value="2015">
                    <input type="hidden" name="arquivo" value="#">
                </div>
            </div>		
            
             <!--EVENTO 03--> 
             <div class="panel" title="Panel 3">
                <div class="wrapper">                   
                    <img src="template/images/slideshow/conhecendo-a-si-mesmo.jpg" alt="temp" />                    
                        <div class="photo-meta-data">
                            Grupo Joanna Convida <br />
                            <span>Conhecendo a si mesmo</span>
                        </div> 
                    <input type="hidden" name="ano" value="2015">
                    <input type="hidden" name="arquivo" value="conhecendo-a-si-mesmo">
                </div>
            </div><!--
            
            
             EVENTO 04 
            <div class="panel" title="Panel 4">
                <div class="wrapper">
                     PANEL CONTENT 
                    <img src="template/images/slideshow/tempphoto-4.jpg" alt="temp" />
                    <div class="photo-meta-data">
                            A Poem by Shel Silverstein<br />
                            <span>Falling Up</span>
                    </div>
                    <input type="hidden" value="4">
                </div>
            </div>
            
             EVENTO 05 
            <div class="panel" title="Panel 5">
                <div class="wrapper">
                     PANEL CONTENT 
                    <img src="template/images/slideshow/tempphoto-5.jpg" alt="temp" />
                    <div class="photo-meta-data">
                            New Video on CSS-Tricks<br />
                            <span>Using Wufoo for Web Forms</span>
                    </div>
                    <input type="hidden" value="5">
                </div>
            </div>
            
             EVENTO 06 
            <div class="panel" title="Panel 6">
                <div class="wrapper">
                     PANEL CONTENT 
                    <h1>A Tale of Two Cities</h1>
                        <p><em>Charles Dickins</em></p>
                        <blockquote>It was the best of times, it was the worst of times, it was the age of 
                            wisdom, it was the age of foolishness, it was the epoch of belief, it was the 
                            epoch of incredulity, it was the season of Light, it was the season of Darkness,
                            it was the spring of hope, it was the winter of despair, we had everything 
                            before us, we had nothing before us, we were all going direct to heaven, we 
                            were all going direct the other way - in short, the period was so far like the
                            present period, that some of its noisiest authorities insisted on its being 
                            received, for good or for evil, in the superlative degree of comparison only.
                        </blockquote>
                    <input type="hidden" value="6">
                </div>                
            </div>-->

        </div>
    </div>

    <!-- TO MAKE THESE THUMBNAILS ACTUALLY WORK, BOTH THE HASH VALUE (#1, ETC.)
      AND THE CLASS="CROSS-LINK" ARE REQUIRED -->

    <a href="#1" class="cross-link active-thumb"><img src="template/images/slideshow/banner-empadao_min.jpg" class="nav-thumb" alt="temp-thumb" /></a>
    <div id="movers-row">
        <div><a href="#2" class="cross-link"><img src="template/images/slideshow/conhecendo-a-si-mesmo_min.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
        <!--<div><a href="#3" class="cross-link"><img src="template/images/slideshow/seminario-saude-espiritismo_min.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>-->
        <!--<div><a href="#4" class="cross-link"><img src="template/images/slideshow/tempphoto-4thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>-->
<!--        <div><a href="#5" class="cross-link"><img src="template/images/slideshow/tempphoto-5thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
        <div><a href="#6" class="cross-link"><img src="template/images/slideshow/tempphoto-6thumb.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>-->
    </div>
</div>