<!-- SLIDESHOW -->
<div class="row">
    <div id="" class="col-md-12">
        <!-- CAROUSEL -->
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2" ></li><!--
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>-->
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
              
<!--            <div class="item active wrapper">
                <img src="template/images/slideshow/vicente-moretti.jpg" alt="..." class="center-block">
                <input type="hidden" name="ano" value="2015">
                <input type="hidden" name="arquivo" value="vicente-moretti">
            </div>              
-->           
            <div class="item active wrapper">
                <img src="template/images/slideshow/seminario-iris-claudio.jpg" alt="..." class="center-block">
                <input type="hidden" name="ano" value="2015">
                <input type="hidden" name="arquivo" value="seminario-iris-claudio">
            </div>

            <div class="item wrapper">
                <img src="template/images/slideshow/aniversario-75-anos-cei.jpg" alt="..." class="center-block">
                <input type="hidden" name="ano" value="2015">
                <input type="hidden" name="arquivo" value="aniversario-75-anos-cei">
            </div>
              
            <div class="item wrapper">
                <img src="template/images/slideshow/conhecendo-a-si-mesmo.jpg" alt="..." class="center-block">
                <input type="hidden" name="ano" value="2015">
                <input type="hidden" name="arquivo" value="conhecendo-a-si-mesmo">
                <div class="carousel-caption">
                    <h3>Grupo Joanna Convida</h3>
                    <p>Conhecendo a si mesmo</p>
                </div>
            </div>
              
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div>  
</div>
