<div id="contato">    
    <div class="padding">
        <form id="formulario" method="POST" autocomplete="off" action="<?=DIR ?>administrator/cadastraProgramacao">
            <div class="tableBlock">
                <!-- NOME -->
                <span class="tableCell">
                    <label class="txtCampos">
                        Nome:
                    </label>
                    <br>
                    <input name="nome" id="nome" style="width: 300px;" value="">
                </span>                
            </div>
            
            <div class="tableBlock">
                <!-- ASSUNTO -->
                <span class="tableCell">
                    <label class="txtCampos">
                        Assunto:
                    </label>
                    <br>
                    <input name="assunto" id="assunto" style="width: 300px;" value="">
                </span>   
            </div>
            
            <div class="tableBlock">
                <!-- E-MAIL -->
                <span class="tableCell">
                    <label class="txtCampos">
                        E-mail:
                    </label>
                    <br>
                    <input name="email" style="width: 300px;" value="">
                </span>   
            </div>  
            
            <div class="tableBlock">
                <!-- MENSAGEM -->
                <span class="tableCell">
                    <label class="txtCampos">
                        Mensagem:
                    </label>
                    <br>
                    <textarea name="msnMail" style="width: 300px; height: 100px;"> </textarea>
                </span>   
            </div>  
            
            <br>
            <a class="botao" id="btnEnviar">
                Enviar
            </a>
        </form>
    </div>
</div>