<div id="evento">
    <h2>Bazar de Natal - 2014</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Venha conferir o nosso Bazar de Natal deste ano!!! Onde você poderá adquirir lindas lembranças confeccionadas com
    muito amor e carinho.</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        De 06 a 16 de Dezembro de 2014
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horários</span>
        <br>
        Dia 06: 15 às 19h<br>
        Dia 08: 14 às 17:30h<br>
        Dia 09: 18 às 20h<br>
        Dia 10: 19 às 19:30h<br>
        Dia 12: 19 às 19:30h<br>
        Dia 13: 15 às 19:30h<br>
        Dia 15: 14 às 17:30h<br>
        Dia 16: 18 às 20h
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Local</span>
        <br>
        2º Piso do CEI
    </div>
</div>
