<div id="evento">
    <h2>Homenagem a Kardec</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_min.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Palestra em homenagem ao codificador da Doutrina Espírita pelo seu aniversário de Nascimento.</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        03 de Outubro de 2014
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Expositor</span>
        <br>
        Gerson Simões Monteiro
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Horário</span>
        <br>
        19:30h
    </div>
</div>
