<div id="evento">
    <h2>Auto Perdão</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_min.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Palestra em homenagem ao codificador da Doutrina Espírita pelo seu aniversário de Nascimento.</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        23 de Setembro de 2014
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Expositor</span>
        <br>
        Marcelo Nazaré (São Paulo)
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Horário</span>
        <br>
        19:00h
    </div>
</div>
