<div id="evento">
    <h2>Seminário Ansiedade e Depressão</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Estudo da ANSIEDADE E DEPRESSÃO, na visão espírita, com base na obra psicológica de Joanna de Ângelis, discutindo 
        suas causas e terapêutica, de forma que seja tratado o Espírito imortal, rumo à saúde integral.  </p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        06 de Dezembro de 2014
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Expositor</span>
        <br>
        Grupo Joanna de Angelis
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Horário</span>
        <br>
        19:00h as 21:00h
    </div>
</div>
