<div id="evento">
    <h2>Seminário Saúde e Espiritismo</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>  </p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        13 de Dezembro de 2014
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Expositores</span>
        <br>
        Área de Assuntos Doutrinários<br>
        Área de Evangelização da Família
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Horário</span>
        <br>
        19:00h as 21:00h
    </div>
</div>