<div class="panel panel-default sessao">
    <div class="panel-body">
        <span class="title_evento">XXII Encontro da Família - Amor em Movimento</span>
    </div>
</div>

<div class="row">    
    <!--CARTAZ--> 
    <div class="col-md-5">
        <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="img">
            <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" class=" img-thumbnail" title="Clique para ver em tamanho normal">
        </a>
    </div>

    <!--TEXTO--> 
    <div class="col-md-7">
        <p class="lead">A Área de Evangelização da Família convida a todos para participarem do evento de abertura
        do Módulo III - Onde estão as suas Mãos?</p>
    </div>
</div> <!-- /div row--> 

<br>

<div class="row">
    <!-- DATA -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Data</div>
            <!-- Panel Body -->
            <div class="panel-body">
                Dia 04 de Julho de 2015
            </div> <!-- /panel-body -->
        </div>        
    </div>

    <!-- EXPOSITOR -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Horários</div>
            <!-- Panel Body -->
            <div class="panel-body">
                Das 16:00 às 18:15h
            </div> <!-- /panel-body -->
        </div>        
    </div>
</div> <!-- /row -->