<div class="panel panel-default sessao">
    <div class="panel-body">
        <span class="title_evento">Aniversário de 75 anos do CEI</span>
    </div>
</div>


<div class="row">    
    <!--CARTAZ--> 
    <div class="col-md-5">
        <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="img">
            <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" class=" img-thumbnail" title="Clique para ver em tamanho normal">
        </a>
    </div>

    <!--TEXTO--> 
    <div class="col-md-7">
        <p class="lead">Amigos, é com imenso prazer que convidamos a todos vocês a participarem da comemorações
        do 75º aniversário do C.E. Ibirajara.</p>
    </div>
</div> <!-- /div row--> 
    
<br>

<div class="row">
    <!-- DATA -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Data</div>
            <!-- Panel Body -->
            <div class="panel-body">
                Dias 16, 23 e 30 de Junho
            </div> <!-- /panel-body -->
        </div>        
    </div>

    <!-- EXPOSITOR -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Horário</div>
            <!-- Panel Body -->
            <div class="panel-body">
                20:10h
            </div> <!-- /panel-body -->
        </div>        
    </div>
    
    <!-- PROGRAMAÇÃO -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Programação</div>
            <!-- Panel Body -->
            <div class="panel-body">
                <strong>Dia 16</strong> - 30 anos de ESDE no CEI<br>
                <strong>Dia 23</strong> - 67 anos do Grupo de Estudos Asdrúbal<br>
                <strong>Dia 30</strong> - 70 anos do retorno de Ibirajara ao plano espiritual
            </div> <!-- /panel-body -->
        </div>        
    </div>
</div> <!-- /row -->