<div id="evento">
    <h2>Capacitação de Evangelizadores</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p></p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        Dia 03 de Março de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horários</span>
        <br>
        Das 09 às 13h
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Local</span>
        <br>
        CEERJ<br>
        Rua dos Inválidos, 182 - Centro
    </div>
    
    <br>
    
    
</div>