<div class="panel panel-default sessao">
    <div class="panel-body">
        <span class="title_evento">Conhecendo a Si Mesmo</span>
    </div>
</div>

<div class="row">    
    <!--CARTAZ--> 
    <div class="col-md-5">
        <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="img">
            <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" class=" img-thumbnail" title="Clique para ver em tamanho normal">
        </a>
    </div>

    <!--TEXTO--> 
    <div class="col-md-7">
        <p class="lead">Grupo de Estudos <span style="color: blueviolet;">Joanna de Ângelis</span> convida você para que venha <b><i>Conhecer a Si Mesmo</i></b> 
    a partir do segundo sábado de Março!</p>
    </div>
</div> <!-- /div row--> 

<br>

<div class="row">
    <!-- DATA -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Data de Início</div>
            <!-- Panel Body -->
            <div class="panel-body">
                Dia 14 de Março de 2015
            </div> <!-- /panel-body -->
        </div>        
    </div>

    <!-- EXPOSITOR -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Horários</div>
            <!-- Panel Body -->
            <div class="panel-body">
                Das 18 às 19:30h (2º e 4º sábados de cada mês)
            </div> <!-- /panel-body -->
        </div>        
    </div>
    
    <!-- LOCAL -->
    <div class="col-md-4">
        <div class="panel panel-info">
            <!-- Panel heading -->
            <div class="panel-heading">Local</div>
            <!-- Panel Body -->
            <div class="panel-body">
                Sala Chico Xavier<br>
                C. E. Ibirajara
            </div> <!-- /panel-body -->
        </div>        
    </div>
</div> <!-- /row -->
