<div id="evento">
    <h2>Conhecendo a Si Mesmo</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Grupo de Estudos <span style="color: blueviolet;">Joanna de Ângelis</span> convida você para que venha <b><i>Conhecer a Si Mesmo</i></b> 
    a partir do segundo sábado de Março!</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data de Início</span>
        <br>
        Dia 14 de Março de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horários</span>
        <br>
        Das 18 às 19:30h (2º e 4º sábados de cada mês)
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Local</span>
        <br>
        Sala Chico Xavier<br>
        C. E. Ibirajara
    </div>
    
    <br>
    
    
</div>