<div id="evento">
    <h2>Enefe - 2015</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Venha participar conosco do Enefe (Encontro Estadual da Família Espírita) de 2015.</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        De 15 a 17 de Fevereiro de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horários</span>
        <br>
        Das 14 às 18h
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Local</span>
        <br>
        Centro Espírita Discípulos de Jesus<br>
        Rua Félix da Cunha, 64 - Tijuca
    </div>
    
    <br>
    
    <div id="horario">
        <span class="destaque">Ficha de Inscrição</span>
        <br>
        Clique <a href="template/images/eventos/2015/ficha_enefe.jpg" target="new"><span style="color: blue;">aqui</span></a> para imprimir a ficha de inscrição
    </div>
</div>
