<div id="evento">
    <h2>Seminário Filho de Deus</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p></p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        Dia 11 de Abril de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horários</span>
        <br>
        Das 19 às 21h
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Coordenação</span>
        <br>
        Grupo de Estudos Joanna de Ângelis
    </div>
    
    <br>
    
    
</div>