<div id="evento">
    <h2>Seminário Conhecendo a Si Mesmo</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" width="200" title="Clique para ver em tamanho normal">
    </a>
    
    <!-- TEXTO -->
    <p>Grupo de Estudos Joana de Ângelis convida você para participar do Seminário 
        <b>"Conhecendo a Si Mesmo"</b> com a Íris e Claudio Sinoti da Mansão do Caminho - Bahia.</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        Dia 16 de Junho de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horário</span>
        <br>
        Das 18 às 19:30h - Estudo aberto do Grupo Joanna<br>
        Das 19:45 às 20:30h - Palestra Pública
    </div>
    <br>
    
    <!-- HORÁRIO -->
<!--    <div id="horario">
        <span class="destaque">Público Alvo</span>
        <br>
        Pais, Evangelizadores e <br>trabalhadores da Casa Espírita.
    </div>
    
    <br>-->
    
    
</div>