<div id="evento">
    <h2>Seminário Autocura e Relação Familiar</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" width="200" title="Clique para ver em tamanho normal">
    </a>
    
    <!-- TEXTO -->
    <p>Grupo Plenitude e Área de Assuntos Doutrinários convida você para participar do Seminário 
        <b>"Autocura e Relação Familiar"</b> com a Dr. Luzia Matias da CELD.</p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        Dia 30 de Maio de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horário</span>
        <br>
        Das 16:30 às 18:30h
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Público Alvo</span>
        <br>
        Pais, Evangelizadores e <br>trabalhadores da Casa Espírita.
    </div>
    
    <br>
    
    
</div>