<div id="evento">
    <h2>Seminário Filho de Deus <span style="color: red;">(Cancelado)</span></h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>_thumb.jpg">
    </a>
    
    <!-- TEXTO -->
    <p>Prezados amigos, <br> Por motivos de complicações no horário do vôo de retorno a Campinas do nosso querido
        Marcelo Nazaré, o mesmo não poderá comparecer ao seminário. A Área de Assuntos Doutrinários achou melhor 
    então adiar o evento para uma nova data a ser escolhida em nosso calendário.</p>
    <p>Pedimos desculpa pelo transtorno causado!<br><br><span style="font-weight: bold;">Att: Área de Assuntos Doutrinários.</span></p>
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        <span style="text-decoration: line-through;">Dia 11 de Abril de 2015</span>
        <br>
        (a ser remarcado)
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horários</span>
        <br>
        Das 19 às 21h
    </div>
    <br>
    
    <!-- HORÁRIO -->
    <div id="horario">
        <span class="destaque">Coordenação</span>
        <br>
        Grupo de Estudos Joanna de Ângelis
    </div>
    
    <br>
    
    
</div>