<div id="evento">
    <h2>Visita à Ação Cristã Vicente Moretti</h2>
    
    <!-- CARTAZ -->
    <a href="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" target="new">
        <img src="template/images/eventos/<?php echo $ano . '/' . $evento; ?>.jpg" width="200" title="Clique para ver em tamanho normal">
    </a>
    
    <!-- TEXTO -->
    <p>A Coordenação da Area de Assistencia e Promoção Social convida a todos para participarem da visita 
        a Ação Cristã Vicente Moretti
    
    <br>
    <!-- DATA -->
    <div id="dia">
        <span class="destaque">Data</span>
        <br>
        Dia 30 de Maio de 2015
    </div>
    <br>
    
    <!-- EXPOSITOR -->
    <div id="expositor">
        <span class="destaque">Horário</span>
        <br>
        Saída do CEI as 13:30h
    </div>
    <br>
    
    <!-- HORÁRIO -->
<!--    <div id="horario">
        <span class="destaque">Público Alvo</span>
        <br>
        Pais, Evangelizadores e <br>trabalhadores da Casa Espírita.
    </div>-->
    
    <br>
    
    
</div>