<div id="adm" class="centraliza">
    <div id="Autentica">
        <div id="superior">
            <img src="system/images/login.png" style="margin-top: 15px;">
        </div>
        <div id="logar">
            <form method="POST" action="control.php">
                <div>
                    <input type="Text" name="usuario" id="usuario" maxlength="50" class="inpLogon" placeholder="Usuário">
                </div>
                <div>
                    <input type="password" name="senha" id="senha" maxlength="50" class="inpLogon" placeholder="Senha">
                </div>
                <div id="resposta" style="color: red;"></div>
                <div>
                    <button type="button" id="btnEntrar">Entrar</button>
                </div>
            </form>
        </div>
    </div>
</div>







