    
    <div class="row">    
        <!--CARTAZ--> 
        <div class="col-md-12">
            <img src="template/images/biblioteca.jpg" class=" img img-responsive" title="Clique para ver em tamanho normal">
        </div>
    </div>

    
    <div class="row">
        <div class="col-md-12">
            <p class="lead">Um bom livro espírita é sempre uma oportunidade para conhecermos a doutrina 
                codificada por Kardec, além de poderoso auxiliar para o nosso aperfeiçoamento espiritual.</p>
        </div>
    </div>
    
    <!-- Pré-requisitos -->
    <div>
        <h4 class="bg-primary">Funcionamento</h4>
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Segunda-feira</b> - de 14:45h às 16:00h</p>
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Terça-feira</b> - de 18:45h às 20:00h</p>
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Quarta-feira</b> - de 19:00h às 20:00h</p>
    </div>
    
    <!-- CEI INDICA -->
    <div>
        <h4 class="bg-primary">CEI Indica</h4>
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Segunda-feira</b> - de 16:00h às 17:00h</p>
            <p><span class="glyphicon glyphicon-time text-info" aria-hidden="true"></span> <b>Terça-feira</b> - de 18:45h às 20:00h</p>
    </div>