<div id="artigo">
    <div class="txt_artigo">
        <b>Um bom livro espírita é sempre uma oportunidade para conhecermos a doutrina codificada por Kardec, 
            além de poderoso auxiliar para o nosso aperfeiçoamento espiritual.
        </b>
    </div>
    <!-- Funcionamento -->
    <div class="txt_artigo">
        <span class="destaque">Funcionamento</span> 
    </div>
    <div>
        <p>
            <span class="boldit">Segunda-feira</span> - De 14:45h às 16:00h
        </p>

        <p>
            <span class="boldit">Terça-feira</span> - De 18:45h às 20:00h
        </p>
        <p>
            <span class="boldit">Quarta-feira</span> - De 19:00h às 20:00h
        </p>
    </div>
    
    <!-- Funcionamento -->
    <div class="txt_artigo">
        <span class="destaque">CEI Indica</span> 
    </div>
    <div>
        <p>
            <span class="boldit">Segunda-feira</span> - De 16:00h às 17:00h
        </p>

        <p>
            <span class="boldit">Terça-feira</span> - De 18:45h às 20:00h
        </p>
    </div>
</div>