<div class="padding">
    
    <!-- PROXIMOS EVENTOS -->
    
    <!-- Seminário Ansiedade e Depressão -->
    <div class="destaque">Próximos Eventos</div>
        <a href="eventos/exibe/2014/seminario-ansiedade-depressao">
            <img src="template/images/eventos/2014/seminario-ansiedade-depressao_thumb.jpg" alt="Homenagem a Kardec" />
        </a>
    
    <hr>
    
    <!-- EVENTOS ANTERIORES -->
    <div>
        <div class="destaque">Eventos Anteriores</div>
        
        <!-- Homenagem a Kardec -->
        <a href="eventos/exibe/2014/homenagem-a-kardec" style="margin-right: 20px;">
            <img src="template/images/eventos/2014/homenagem-a-kardec_min.jpg" alt="Homenagem a Kardec" />
        </a>
        
        <!-- Auto-perdão -->
        <a href="eventos/exibe/2014/marcelo-nazare-auto-perdao">
            <img src="template/images/eventos/2014/marcelo-nazare-auto-perdao_min.jpg" alt="Marcelo Nazaré" />
        </a>
    </div>    
</div>