<div class="padding">
    
    <!-- PROXIMOS EVENTOS -->
    
    
    <div class="destaque">Eventos Anteriores - 2015</div>
    
    <!-- Seminário Saúde e Espiritismo -->
    <a href="eventos/exibe/2015/enefe-2015">
        <img src="template/images/eventos/2015/enefe-2015_thumb.jpg" width="125" title="Enefe 2015" />
    </a>
       
    
    <!--<hr>-->
    
    <!-- EVENTOS ANTERIORES -->
    <div>
        <div class="destaque">Eventos Anteriores - 2014</div>
        
        <!-- Seminário Saúde e Espiritismo -->
        <a href="eventos/exibe/2014/seminario-saude-espiritismo">
            <img src="template/images/eventos/2014/seminario-saude-espiritismo_thumb.jpg" width="125" title="Seminário Saúde e Espiritismo" />
        </a>
        
        <!-- Seminário Ansiedade e Depressão -->
        <a href="eventos/exibe/2014/seminario-ansiedade-depressao">
            <img src="template/images/eventos/2014/seminario-ansiedade-depressao_thumb.jpg" width="125" title="Ansiedade e Depressão" />
        </a>
        
        <!-- Homenagem a Kardec -->
        <a href="eventos/exibe/2014/homenagem-a-kardec">
            <img src="template/images/eventos/2014/homenagem-a-kardec_min.jpg" width="125" title="Homenagem a Kardec" />
        </a>
        
        <!-- Auto-perdão -->
        <a href="eventos/exibe/2014/marcelo-nazare-auto-perdao">
            <img src="template/images/eventos/2014/marcelo-nazare-auto-perdao_min.jpg" width="125" title="Marcelo Nazaré" />
        </a>
    </div>    
</div>