<div id="mensagem">
    <div class="titulo_mess">
        Mensagem
    </div>
    <div class="campo_mess">
        <img class="ico_mess" src="<?=DIR ?>system/images/<?php echo 'ico_'.$this->_tipo.'_grd.png'; ?>">
        <span class="msn_alerta" style="color: <?php echo $this->cor; ?>"><?php echo $this->dizer; ?></span>
        <p class="msn_mess"><?php echo $msn; ?></p>
        
        <a class="btn_mess botao"  href="<?php echo DIR . $this->_URL; ?>">
            OK
        </a>
    </div>
</div>