<div id="mes" class="mes">
    <!-- PERIODO -->
    <div class="titMes">
        JANEIRO de 2015
    </div>

    <!-- SEGUNDA -->
    <div class="week">                
        <div class="semana">
            <span  class="dia_semana">SEGUNDAS-FEIRAS - 15h</span>
            <br>
            <!-- Estudo -->
            <span class="estudo">Estudo de "O Evangelho segundo o Espiritismo"</span>
        </div>
        <!-- PROGRAMAÇAO DIA-->
        <div class="programaDia">
            <div class="dia">
                <!-- Dia -->
                <span class="dtDia">05</span>
            </div>
            <span class="fundo">
                <!-- Tema -->
                <span class="tema">
                    <span style="color: #006; font-weight: bold;">Tema:</span>
                    "O amor e a caridade construindo uma Nova Sociedade"
                </span>
                <br>
                <!-- Expositor -->
                <span class="expositor">
                    <span style="color: #006; font-weight: bold;">Expositor:</span> Ana Beatriz Lima 
                </span>
            </span>
        </div>
        
        <!-- PROGRAMAÇAO DIA-->
        <div class="programaDia">
            <div class="dia">
                <!-- Dia -->
                <span class="dtDia">12</span>
            </div>
            <span class="fundo">
                <!-- Tema -->
                <span class="tema">
                    <span style="color: #006; font-weight: bold;">Tema:</span>
                    "O Pai Nosso"
                </span>
                <br>
                <!-- Expositor -->
                <span class="expositor">
                    <span style="color: #006; font-weight: bold;">Expositor:</span> Maria Helena Hollanda
                </span>
            </span>
        </div>
        
        <!-- PROGRAMAÇAO DIA-->
        <div class="programaDia">
            <div class="dia">
                <!-- Dia -->
                <span class="dtDia">19</span>
            </div>
            <span class="fundo">
                <!-- Tema -->
                <span class="tema">
                    <span style="color: #006; font-weight: bold;">Tema:</span>
                    "O carneirinho Revoltado"
                </span>
                <br>
                <!-- Expositor -->
                <span class="expositor">
                    <span style="color: #006; font-weight: bold;">Expositor:</span> Silvia Gomes
                </span>
            </span>
        </div>
        
        <!-- PROGRAMAÇAO DIA-->
        <div class="programaDia">
            <div class="dia">
                <!-- Dia -->
                <span class="dtDia">26</span>
            </div>
            <span class="fundo">
                <!-- Tema -->
                <span class="tema">
                    <span style="color: #006; font-weight: bold;">Tema:</span>
                    "A restauração do Inferno"
                </span>
                <br>
                <!-- Expositor -->
                <span class="expositor">
                    <span style="color: #006; font-weight: bold;">Expositor:</span> Ana Beatriz Lima
                </span>
            </span>
        </div>
        
        <!-- PROGRAMAÇAO DIA-->
<!--        <div class="programaDia">
            <div class="dia">
                 Dia 
                <span class="dtDia">29</span>
            </div>
            <span class="fundo">
                 Tema 
                <span class="tema">
                    <span style="color: #006; font-weight: bold;">Tema:</span>
                    "Jesus e os homens" (Antologia Mediúnica do Natal, F.C.Xavier/Espíritos Diversos, cap. 76) 
                </span>
                <br>
                 Expositor 
                <span class="expositor">
                    <span style="color: #006; font-weight: bold;">Expositor:</span> Ana Beatriz Lima
                </span>
            </span>
        </div>-->
        
    </div>

   

    <!-- TERÇA -->
    <div class="semana">                
        <div class="dia_semana">
            TERÇAS-FEIRAS - 20h10min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            &nbsp;
        </div>
    </div>

    <!-- PROGRAMAÇAO 01-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            06
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Servindo com alegria! - APSE, o que é? 
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Equipe APSE/CEI
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 02-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            13
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Caridade, sublime virtude para a felicidade. Vamos ao ENEFE?"
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Ricardo Bedirian
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 03-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            20
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Fé" (ESE, cap. XIX; Estudos Espíritas,Joanna de Ângelis/Divaldo Franco)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Dayse Lourenço
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- PROGRAMAÇAO 04-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            27
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Esperança" (ESE, cap. XV; Estudos Espíritas, Joanna de Ângelis/Divaldo Franco)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Telma Cerqueira (CEJN) 
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- PROGRAMAÇAO 05-->
<!--    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                         Dia 
                        <div >
                            30
                        </div>
                    </td>
                    <td class="fundo">
                         Tema 
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Jesus, o Líder"  (Baseado na obra de Divaldo Franco/J.Ângelis, Amélia Rodrigues)                            
                        </span>
                        <br>
                         Expositor 
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Dayse Lourenço
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>-->

    <!-- QUARTA -->
    <div class="semana">                
        <div class="dia_semana">
            QUARTAS-FEIRAS - 19h30min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            Estudo aprofundado da Doutrina Espírita - (FEB)
        </div>
    </div>

    <!-- PROGRAMAÇAO 01-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            07
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "A Negação de Pedro" ( Boa Nova, F.C.Xavier/Humberto de Campos, cap. 26)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Maria Helena Hollanda
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 02-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            14
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Maria de Magdala" (Boa Nova, F.C.Xavier/Humberto de Campos, cap. 20)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Silvia Gomes
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 03-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            21
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "O Servo Bom-Zaqueu" ( Boa Nova, F.C.Xavier/Humberto de Campos, cap. 23)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Suely Pumar
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- PROGRAMAÇAO 04-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            28
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "O Bom Ladrão" (Boa Nova, F.C.Xavier/Humberto de Campos, cap. 28) 
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Suely Olivieri
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- PROGRAMAÇAO 05-->
    <!--            <div class="borda_baixo">
                    <table cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td class="dia">
                                     Dia 
                                    <div >
                                        30
                                    </div>
                                </td>
                                <td class="fundo">
                                     Tema 
                                    <span class="tema">
                                        <span style="color: #006; font-weight: bold;">Tema:</span>
                                        "O Homem Novo" ( Pão Nosso, F.C.Xavier/Emmanuel, caps. 41,68,138/9 e 154;Vinha de Luz,F.C.X/Emmanuel, caps.24 e 28)
                                    </span>
                                    <br>
                                     Expositor 
                                    <span class="expositor">
                                        <span style="color: #006; font-weight: bold;">Expositor:</span> Denise Xavier(Casa da Caridade)
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>-->

    <!-- SEXTA -->
    <div class="semana">                
        <div class="dia_semana">
            SEXTAS-FEIRAS - 19h30min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            Estudo de “O Livro dos Espíritos”
        </div>
    </div>

    <!-- PROGRAMAÇAO 01-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            02
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            NÃO HÁ REUNIÃO
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> 
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 02-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            09
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Escolha das provas" (pergs. 258 a 264)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Manoel Messias
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 03-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            16
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Escolha das provas" (pergs. 265 a 273)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Angela Delou
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- PROGRAMAÇAO 04-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            23
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "As relações ..." (pergs. 274 a 290)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Dayse Lourenço
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <!-- PROGRAMAÇAO 05-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            30
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Relações de simpatia ..." (pergs. 291 a 303)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Angela Rodrigues
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- SABADO -->
    <div class="semana">                
        <div class="dia_semana">
            SABADOS - 19h45min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            Tríplice Aspecto da Doutrina Espírita
        </div>
    </div>

    <!-- PROGRAMAÇAO 01-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            03
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            NÃO HÁ REUNIÃO
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> 
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 02-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            10
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Honestidade emocional" (Convites ao enfrentamento, Fernando de Luna/M.Nazareth, cap. 2)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Rosana Cruz
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>            
    <!-- PROGRAMAÇAO 03-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            17
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "O vitral do ego" (Convites ao enfrentamento, Fernando de Luna/M.Nazareth, cap. 3) 
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Shirley Elias
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- PROGRAMAÇAO 04-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            24
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Análise dos Sofrimentos" (Plenitude, Divaldo Franco/Joanna de Ângelis, cap. II) 
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Gabriel Mendes
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <!-- PROGRAMAÇAO 05-->
    <div class="borda_baixo">
        <table cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td class="dia">
                        <!-- Dia -->
                        <div >
                            31
                        </div>
                    </td>
                    <td class="fundo">
                        <!-- Tema -->
                        <span class="tema">
                            <span style="color: #006; font-weight: bold;">Tema:</span>
                            "Origens do Sofrimento" (Plenitude, Divaldo Franco/Joanna de Ângelis, cap. III)
                        </span>
                        <br>
                        <!-- Expositor -->
                        <span class="expositor">
                            <span style="color: #006; font-weight: bold;">Expositor:</span> Alvaro Luiz da Silva
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>