<?php
// Verifica qual o mes corrente
switch ($dados['mes'])
{
    case 01:
        $mes = "JANEIRO";
        break;
    case 02:
        $mes = 'FEVEREIRO';
        break;
    case 03:
        $mes = 'MARÇO';
        break;
    case 04:
        $mes = 'ABRIL';
        break;
    case 05:
        $mes = 'MAIO';
        break;
    case 06:
        $mes = 'JUNHO';
        break;
    case 07:
        $mes = 'JULHO';
        break;
    case 08:
        $mes = 'AGOSTO';
        break;
    case 09:
        $mes = 'SETEMBRO';
        break;
    case 10:
        $mes = 'OUTUBRO';
        break;
    case 11:
        $mes = 'NOVEMBRO';
        break;
    case 12:
        $mes = 'DEZEMBRO';
        break;
}

$ano = $dados['ano'];

unset($dados['mes'], $dados['ano']);

?>

<div id="mes" class="mes">
    
    <!-- PERIODO -->
    <div class="titMes">
        <?php echo $mes; ?> de <?php echo $ano; ?>
    </div>
    
    <!-- SEGUNDA -->
    <div class="week">  
        <div class="semana">
            <span  class="dia_semana">SEGUNDA - 15h</span>
            <br>
            <!-- Estudo -->
            <span class="estudo">Estudo de "O Evangelho segundo o Espiritismo"</span>
        </div>
    
    <?php 
    foreach ($dados as $programacao): 
        $d = date('w', strtotime($programacao['data']));

        if($d == 1)
        { ?>
            <!-- PROGRAMAÇAO DIA-->
            <div class="programaDia">
                <div class="dia">
                    <!-- Dia -->
                    <span class="dtDia"><?php echo date('d', strtotime($programacao['data'])); ?></span>
                </div>
                <span class="fundo">
                    <!-- Tema -->
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        <?php echo $programacao['tema']; ?>
                    </span>
                    <br>
                    <!-- Expositor -->
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programacao['expositor']; ?> 
                    </span>
                </span>
            </div> <?php
        } 
    endforeach; ?>
    </div>    
    
    
    <!-- TERÇA -->
    <div class="semana">                
        <div class="dia_semana">
            TERÇAS-FEIRAS - 20h10min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            &nbsp;
        </div>
    </div>
    
    <?php 
    foreach ($dados as $programacao): 
        $d = date('w', strtotime($programacao['data']));

        if($d == 2)
        { ?>
            <!-- PROGRAMAÇAO DIA-->
            <div class="programaDia">
                <div class="dia">
                    <!-- Dia -->
                    <span class="dtDia"><?php echo date('d', strtotime($programacao['data'])); ?></span>
                </div>
                <span class="fundo">
                    <!-- Tema -->
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        <?php echo $programacao['tema']; ?>
                    </span>
                    <br>
                    <!-- Expositor -->
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programacao['expositor']; ?> 
                    </span>
                </span>
            </div> <?php
        } 
    endforeach; ?>
            
    
    <!-- QUARTA -->
    <div class="semana">                
        <div class="dia_semana">
            QUARTAS-FEIRAS - 19h30min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            Estudo aprofundado da Doutrina Espírita - (FEB)
        </div>
    </div>
    
    <?php 
    foreach ($dados as $programacao): 
        $d = date('w', strtotime($programacao['data']));

        if($d == 3)
        { ?>
            <!-- PROGRAMAÇAO DIA-->
            <div class="programaDia">
                <div class="dia">
                    <!-- Dia -->
                    <span class="dtDia"><?php echo date('d', strtotime($programacao['data'])); ?></span>
                </div>
                <span class="fundo">
                    <!-- Tema -->
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        <?php echo $programacao['tema']; ?>
                    </span>
                    <br>
                    <!-- Expositor -->
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programacao['expositor']; ?> 
                    </span>
                </span>
            </div> <?php
        } 
    endforeach; ?>
    
            
    <!-- SEXTA -->
    <div class="semana">                
        <div class="dia_semana">
            SEXTAS-FEIRAS - 19h30min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            Estudo de “O Livro dos Espíritos”
        </div>
    </div>
    
    <?php 
    foreach ($dados as $programacao): 
        $d = date('w', strtotime($programacao['data']));

        if($d == 5)
        { ?>
            <!-- PROGRAMAÇAO DIA-->
            <div class="programaDia">
                <div class="dia">
                    <!-- Dia -->
                    <span class="dtDia"><?php echo date('d', strtotime($programacao['data'])); ?></span>
                </div>
                <span class="fundo">
                    <!-- Tema -->
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        <?php echo $programacao['tema']; ?>
                    </span>
                    <br>
                    <!-- Expositor -->
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programacao['expositor']; ?> 
                    </span>
                </span>
            </div> <?php
        } 
    endforeach; ?>
            
            
    <!-- SABADO -->
    <div class="semana">                
        <div class="dia_semana">
            SABADOS - 19h45min
        </div>
        <!-- Estudo -->
        <div class="estudo">
            Tríplice Aspecto da Doutrina Espírita
        </div>
    </div>
    
     <?php 
    foreach ($dados as $programacao): 
        $d = date('w', strtotime($programacao['data']));

        if($d == 6)
        { ?>
            <!-- PROGRAMAÇAO DIA-->
            <div class="programaDia">
                <div class="dia">
                    <!-- Dia -->
                    <span class="dtDia"><?php echo date('d', strtotime($programacao['data'])); ?></span>
                </div>
                <span class="fundo">
                    <!-- Tema -->
                    <span class="tema">
                        <span style="color: #006; font-weight: bold;">Tema:</span>
                        <?php echo $programacao['tema']; ?>
                    </span>
                    <br>
                    <!-- Expositor -->
                    <span class="expositor">
                        <span style="color: #006; font-weight: bold;">Expositor:</span> <?php echo $programacao['expositor']; ?> 
                    </span>
                </span>
            </div> <?php
        } 
    endforeach; ?>
</div>